version: '3.8'

services:
  grpc_cv_service:
    container_name: grpc-cv-service
    build:
      context: ./grpc-vision-svc
      target: final
    networks:
      - skynet
    ports:
      - 50051:50051
    env_file:
      - ./grpc-vision-svc/.env

networks:
  skynet:
