version: '3.8'

services:
  grpc_cv_service:
    container_name: grpc-cv-service
    build:
      context: ./grpc-vision-svc
      target: final
    volumes:
      - /home/${USER}/.cache/huggingface/:/nonexistent/.cache/huggingface/
    networks:
      - skynet
    ports:
      - 50051:50051
    environment:
      - RUST_LOG=INFO
      - VISION_ADDR=[::]:50051

networks:
  skynet:
