pub mod proto {
    //! This module defines the protocol buffer definitions and related constants for the Computer Vision service.
    //!
    //! It includes the compiled gRPC service definitions and the file descriptor set for the `computer_vision`
    //! service. The `proto` module is generated by `tonic` from the `.proto` files and contains the necessary
    //! structures and services for gRPC communication.
    tonic::include_proto!("computer_vision");
    
    /// A constant that includes the file descriptor set for the vision service.
    pub const FILE_DESCRIPTOR_SET: &[u8] = tonic::include_file_descriptor_set!("vision_svc_descriptor");
}

pub mod service_impl;
pub mod image_captioning;
//pub mod middleware;
