name: Auth Service CI

on:
  push:
    branches:
      - auth-svc

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install
      working-directory: ./auth-svc

    - name: Run Tests
      run: npm run test
      working-directory: ./auth-svc
