name: CV Service CI

on:
  push:
    branches: ["main", "grpc-vision-svc"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            grpc-vision-svc/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build
        working-directory: grpc-vision-svc
        run: cargo build --verbose
          
      - name: Run tests
        working-directory: grpc-vision-svc
        run: cargo test --all-targets --verbose
        
      - name: Run Clippy
        working-directory: grpc-vision-svc
        run: cargo clippy --all-targets --all-features
