name: Docs

on:
  push:
    branches: ["grpc-vision-svc"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Protobuf
        run: sudo apt-get install protobuf-compiler
              
      - name: Checkout sources
        uses: actions/checkout@v4
    
      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v4
      
      - name: Clean docs folder
        working-directory: grpc-vision-svc
        run: cargo clean --doc
      
      - name: Build docs
        working-directory: grpc-vision-svc
        run: cargo doc --no-deps
      
      - name: Add redirect
        working-directory: grpc-vision-svc
        run: echo '<meta http-equiv="refresh" content="0;url=grpc_vision_svc/index.html">' > target/doc/index.html
      
      - name: Remove lock file
        working-directory: grpc-vision-svc
        run: rm target/doc/.lock
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: grpc-vision-svc/target/doc
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
